export const NEWSLETTER_SUBSCRIBE_REQUEST = 'NEWSLETTER_SUBSCRIBE_REQUEST';
export const NEWSLETTER_SUBSCRIBE_SUCCESS = 'NEWSLETTER_SUBSCRIBE_SUCCESS';
export const NEWSLETTER_SUBSCRIBE_ERROR = 'NEWSLETTER_SUBSCRIBE_ERROR';

export const NEWSLETTER_SET_EMAIL = 'NEWSLETTER_SET_EMAIL';
export const NEWSLETTER_RESET = 'NEWSLETTER_RESET';
export const NEWSLETTER_POPUP_DISMISS = 'NEWSLETTER_POPUP_DISMISS';